software/PersonelApp/PersonelApp.Web/Controllers/DerslerController.cs
using Microsoft.AspNetCore.Mvc;
using PersonelApp.Web.Models;

namespace PersonelApp.Web.Controllers
{
    public class DerslerController : Controller
    {
        private AppDbContext _context;

        private readonly DerslerRepository _derslerRepository;
        private readonly DerslerAyrintiRepository _derslerAyrintiRepository;
        private readonly BlogRepository _blogRepository;
        private readonly YoneticiRepository _yoneticiRepository;
        private readonly DuyurularRepository _duyurularRepository;
        private readonly LinkRepository _linkRepository;
        public DerslerController(AppDbContext context)
        {
            _derslerRepository = new DerslerRepository();
            _derslerAyrintiRepository = new DerslerAyrintiRepository();
            _blogRepository = new BlogRepository();
            _yoneticiRepository = new YoneticiRepository();
            _duyurularRepository = new DuyurularRepository();
            _linkRepository = new LinkRepository();
            _context = context;
        }
        public IActionResult Index()
        {
            var bloglar = _context.Bloglar.ToList();
            var dersler = _context.Dersler.ToList();
            var yonetici = _context.Yonetici.ToList();
            var duyurular = _context.Duyurular.ToList();
            var linkler = _context.Linkler.ToList();
            ViewBag.Linkler = linkler;
            ViewBag.Duyurular = duyurular;
            ViewBag.Yonetici = yonetici;
            ViewBag.Bloglar = bloglar;
            ViewBag.Dersler = dersler;

            return View();
        }

        public IActionResult DersAyrintilar(int id)
        {
            var bloglar = _context.Bloglar.ToList();
            var dersler = _context.Dersler.ToList();
            var dersAyrintilar = _context.DersAyrintilar.ToList();
            var yonetici = _context.Yonetici.ToList();
            var duyurular = _context.Duyurular.ToList();
            var linkler = _context.Linkler.ToList();
            ViewBag.Linkler = linkler;
            ViewBag.Duyurular = duyurular;
            ViewBag.Yonetici = yonetici;
            ViewBag.CurrentId = id;
            ViewBag.Bloglar = bloglar;
            ViewBag.Dersler = dersler;
            ViewBag.DersAyrintilar = dersAyrintilar;
            return View();
        }
    }
}

software/PersonelApp/PersonelApp.Web/Views/Dersler/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<style>
    @@media (max-width: 768px) {
        .col-2 {
            display: none; /* Side menu'yu gizler */
        }

        .col-10 {
            width: 100%; /* İçeriği tam genişlikte kaplatır */
            margin: 0 auto; /* Ortalar */
        }

        .content-container {
            padding: 10px; /* Küçük ekranlarda daha az padding */
        }

        .row .col-6 {
            flex: 0 0 100%; /* Kartların tamamını bir satırda kaplamasını sağlar */
            max-width: 100%;
            margin-bottom: 1rem !important;
        }

        .card-text{
            display: none;
        }
    }
    .card {
        transition: transform 0.3s ease, box-shadow 0.3s ease;
    }

        .card:hover {
            transform: scale(1.02); /* Kartın hafifçe büyümesini sağlar */
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3); /* Gölge efekti ekler */
        }
    /* Kenar çubuğu */
    .col-2 {
        style ="background: linear-gradient(180deg, #141e30, #0d1b2a); color: #fff;
        padding-top: 20px;
        min-height: 100vh;
    }

    .container-fluid {
        overflow-x: hidden;
    }

    @@media (min-width: 769px) {
        .dropdown-container {
            display: none;
        }
    }
</style>

<partial name="_MobileSidebarPartialView" />

<div class="container-fluid">
    <div class="row">
        <div class="col-2">
            <partial name="_MainSidebarPartialView" />
        </div>
        <div class="col-10">
            <div class="row mt-2 mb-3">
                @for (int i = 0; i < ViewBag.Dersler.Count; i += 4)
                {
                    <div class="col-6 mb-3">
                        <a asp-controller="Dersler" asp-action="DersAyrintilar" asp-route-id="1">
                            <div class="card bg-dark text-white">
                                <img class="card-img" src="@ViewBag.Dersler[i].Img" alt="Card image">
                                <div class="card-img-overlay">
                                    <p class="card-text">@ViewBag.Dersler[i].Content</p>
                                    <p class="card-text">@ViewBag.Dersler[i].Date</p>
                                </div>
                            </div>
                        </a>
                    </div>

                    @if (i + 1 < ViewBag.Dersler.Count)
                    {
                        <div class="col-6">
                            <a asp-controller="Dersler" asp-action="DersAyrintilar" asp-route-id="2">
                                <div class="card bg-dark text-white">
                                    <img class="card-img" src="@ViewBag.Dersler[i+1].Img" alt="Card image">
                                    <div class="card-img-overlay">
                                        <p class="card-text">@ViewBag.Dersler[i + 1].Content</p>
                                        <p class="card-text">@ViewBag.Dersler[i + 1].Date</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    }

                    @if (i + 2 < ViewBag.Dersler.Count)
                    {
                        <div class="col-6">
                            <a asp-controller="Dersler" asp-action="DersAyrintilar" asp-route-id="3">
                                <div class="card bg-dark text-white">
                                    <img class="card-img" src="@ViewBag.Dersler[i+2].Img" alt="Card image">
                                    <div class="card-img-overlay">
                                        <p class="card-text">@ViewBag.Dersler[i + 2].Content</p>
                                        <p class="card-text">@ViewBag.Dersler[i + 2].Date</p>
                                    </div>
                                </div>
                            </a>

                        </div>
                    }

                    @if (i + 3 < ViewBag.Dersler.Count)
                    {
                        <div class="col-6">
                            <a asp-controller="Dersler" asp-action="DersAyrintilar" asp-route-id="4">
                                <div class="card bg-dark text-white">
                                    <img class="card-img" src="@ViewBag.Dersler[i+3].Img" alt="Card image">
                                    <div class="card-img-overlay">
                                        <p class="card-text">@ViewBag.Dersler[i + 3].Content</p>
                                        <p class="card-text">@ViewBag.Dersler[i + 3].Date</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    }
                }
            </div>
        </div>
    </div>
</div>